### ISSUE TITLE
Retroactive Funding Experiement: Pre Production

### ISSUE THREAD

**Issue by PardusEidolon** [yumiai/yumi-videos#7]
## Overview
This is story is to document the pre-production pipeline for #6. This will include scripts storyboards and rough animation ideas for the video.

## Tasks
- [ ] Story boards drafts script
- [ ] Revised Scripts
- [ ] Video Structure outine 
- [ ] Create new assets
