### ISSUE TITLE
Retroactive Funding Experiement: Production

### ISSUE THREAD

**Issue by PardusEidolon** [yumiai/yumi-videos#8]
## Overview
This is story is to document the pre-production pipeline for #6. This will include scripts storyboards and rough animation ideas for the video.

## Tasks
- [ ] Animation Begins
- [ ] Create new assets
- [ ] Wrap-Animation

## Merging pre-production content
When the documents have been created, the Pull Request will be checked, and any fixes applied. The pull request is then merged and published when the main repository

- [ ] Retroactive Funding Experiment Prodction PR Merged
   - [ ] Retroactive Funding Experiment Animations reviewed and checked
   - [ ] Retroactive Funding Experiment Assets reviewed and checked
