### ISSUE TITLE
Retroactive Funding Experiement: Post Production

### ISSUE THREAD

**Issue by PardusEidolon** [yumiai/yumi-videos#9]
## Overview
This is story is to document the pre-production pipeline for #6. This will include any Dialogue Recording, Video Editing, Sound effects and mixing etc.

## Tasks
- [ ] Cut, Compose,Mix and add SFX
- [ ] Final Review
- [ ] Upload to Youtube and Include in Ideascale

## Merging pre-production content
When the documents have been created, the Pull Request will be checked, and any fixes applied. The pull request is then merged and published when the main repository

- [ ] Retroactive Funding Experiment Post-Production PR Merged
   - [ ] Retroactive Funding Experiment Rough cut reviewed and checked
   - [ ] Retroactive Funding Experiment Final cut reviewed and checked
   - [ ] Retroactive Funding Experiment Videos uploaded and shared reviewed and checked
